### ISSUE TITLE
Cannot run test case

### ISSUE THREAD

**Issue by daquang** [jmschrei/avocado#2]
When I run the command model.fit(data, n_epochs=10, epoch_size=100) I get the following error:

/media/data/daquang/Software/avocado/avocado/model.py:443: UserWarning: Update your `fit_generator` call to the Keras 2 API: `fit_generator(<generator..., 100, 10, workers=1, verbose=1, callbacks=None, use_multiprocessing=True)`
  callbacks=callbacks, **kwargs)
Epoch 1/10
Traceback (most recent call last):
  File "/home/daquang/anaconda3/lib/python3.6/site-packages/keras/utils/data_utils.py", line 677, in _data_generator_task
    generator_output = next(self._generator)
  File "/media/data/daquang/Software/avocado/avocado/io.py", line 55, in sequential_data_generator
    value[i]         = tracks[idx][genomic_25bp_idxs[i]]
TypeError: 'dict_values' object does not support indexing

Can you also include a script to convert raw files (eg bigwigs) into the appropriate npz files? This will be useful if we want to run our own models.

**Comment by jmschrei** [comment]
Howdy

It looks like that problem is coming from https://github.com/jmschrei/avocado/blob/master/avocado/io.py#L40 where I unpack the values of the dictionary. This works in Python 2, but not Python 3. If you'd like to try updating it on your end you can change that to `tracks = list(data.values())`. 

There are several ways that one can convert between bigWigs and npz files. The easiest is likely using pyBigWig (https://github.com/deeptools/pyBigWig). Using that you can open a bigWig and extract a numpy array. You can then downsample from 1 bp resolution to 25 bp resolution easily by doing something like `track = track[track.shape[0] // 25 * 25].reshape(track.shape[0] // 25, 25).mean(axis=1)` for each chromosome.

**Comment by daquang** [comment]
Thanks for the tip, it worked. Now I can run it on the test case in Python 3.

I'm guessing that in order to get it working on my own data, I have to generate 25 bp resolution .npz tracks for each chromosome, and train a model for each chromosome? Would a single model trained on the entire genome consume too much memory? Just trying to understand this particular design choice.

**Comment by jmschrei** [comment]
Unfortunately, training a single model across the entire genome is infeasible due to memory issues, as you guessed. You can imagine that, for a model with 100 latent factors, that you would end up needing to store an embedding matrix with  3 billion / 25 * 100 = 12 billion values in it. This would take ~48 gigabytes when using 32 bit floats, which won't fit on most commercial GPUs. 

To get around this, Avocado has a two-stage procedure which you can read more about in the paper. Essentially, you fit the model to the ENCODE Pilot Regions (~1.2 million positions at 25 bp resolution), freeze the neural network, cell type, and assay factors, and then you fit the genome factors independently for each chromosome. The fixed NN and other factors ensure that the learned genome factors are comparable across chromosomes. If you don't care about the factors being comparable across chromosomes and just want good imputation performance, you can fit a separate model per chromosome.
